baseurl = "https://sysbiowebsite.netlify.com/"
title = "Systems and Synthetic Biology - SYSBIO"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu
[[menu.main]]
  name = "News"
  url  = "/news/"
  weight = 1
[[menu.main]]
  name = "tools"
  identifier = "tools"
  url  = "/tools/"
  weight = 2
  hasChildren = true
[[menu.main]]
  Name = "Software"
  parent = "tools"
  URL = "/tools/software"
  Weight = 1.0
[[menu.main]]
  Name = "Databases"
  parent = "tools"
  URL = "/tools/databases"
  Weight = 2.0
[[menu.main]]
  Name = "GEMs"
  parent = "tools"
  URL = "/tools/GEMs"
  Weight = 3.0
[[menu.main]]
  name = "Projects"
  url  = "/international-projects/"
  weight = 3
[[menu.main]]
  name = "About"
  identifier = "about"
  weight = 4
  hasChildren = true
[[menu.main]]
  Name = "People"
  parent = "about"
  URL = "/about/people"
  Weight = 1.0
[[menu.main]]
  Name = "Group Photos"
  parent = "about"
  URL = "/about/photos"
  Weight = 2.0
[[menu.main]]
  name = "Contact"
  url  = "/contact/"
  weight = 6

# Enable or disable top bar with social icons
[params.topbar]
  enable = false
  text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
    <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
    <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
    </p>
    """
# Top bar social links menu
[[menu.topbar]]
  weight = 1
  name = "GitHub"
  url = "https://github.com/SysBioChalmers"
  pre = "<i class='fa fa-2x fa-github'></i>"

[params]
  viewMorePostLink = "/news/"
  author = "Martina"
  defaultKeywords = ["devows", "hugo", "go"]
  defaultDescription = "Site template made by devcows using hugo"

  # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
  style = "blue"

  # Since this template is static, the contact form uses www.formspree.io as a
  # proxy. The form makes a POST request to their servers to send the actual
  # email. Visitors can send up to a 1000 emails each month for free.
  # What you need to do for the setup?
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email yourself to confirm your account
  # - click the confirm link in the email from www.formspree.io
  # - you're done. Happy mailing!
  # Enable the contact form by entering your Formspree.io email
  email = "your@email.com"

  about_us = "img/chalmers.png"
  copyright = "Sysbio © 2018 "

  # Format dates with Go's time formatting
  date_format = "January 2, 2006"

  logo = "img/logo.png"
  address = """<p><strong>Chalmers University of Technology</strong>
      <br>Department of Biology and Biological Engineering
      <br>Division of Systems and Synthetic Biology
      <br>Kemivägen 10
      <br>SE-412 96 Göteborg
      <br>
      <strong>Sweden</strong>
    </p>
    """
  latitude = "57.690795"
  longitude = "11.977283"

[Permalinks]
  news = "/news/:year/:month/:day/:filename/"

# Enable and disable widgets for the right sidebar
[params.widgets]
  categories = true
  tags = true
  search = true

[params.features]
  enable = false
  # All features are defined in their own files. You can find example items
  # at 'exampleSite/data/features'.
  # For more informtion take a look at the README.

[params.labs]
  enable = true
  # All labs are defined in their own files. You can find example items
  # at 'data/labs'.
  title = "Labs"
  subtitle = ""

[params.see_more]
  enable = true
  icon = "fa fa-flask"
  title = "International projects"
  subtitle = "Check out some of our latest and most exciting international projects"
  link_url = "/projects"
  link_text = "Explore"

[params.centres]
  enable = true
  # All centres are defined in their own files. You can find example items at 'data/centres'.
  title = "Centers of Excellence"
  subtitle = "Systems and Synthetic Biology is part of four large center structures that operate with satellite facilities at Chalmers."

[params.recent_news]
  enable = true
  title = "Recent news"
  subtitle = ""

[params.organization]
  enable = true
  title = "Organization"
  subtitle = "The division of Systems and Synthetic Biology is part of the new **[Department of Biology and Biological Engineering](http://www.chalmers.se/en/departments/bio/)**.<br>Systems and Synthetic Biology is headed by Professor Jens Nielsen and is composed of several labs and faculty. Each lab has a leader  who is responsible for directing particular research themes. The lab and computational facilities are shared among all members of Systems and Synthetic Biology.<br> Systems and Synthetic Biology has a central role in LifeScience@Chalmers, which is one of eight **[Areas of Advance](http://www.chalmers.se/en/areas-of-advance/lifescience/)** at Chalmers University of Technology. The director of Life Science Engineering Area of Advance is Professor Ivan Mijakovic."
  image = "img/organization.jpg"
