baseurl = "https://sysbiowebsite.netlify.com/"
title = "Systems and Synthetic Biology - SYSBIO"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu
[[menu.main]]
  name = "People"
  url  = "/people/"
  weight = 1
[[menu.main]]
  name = "News"
  url  = "/news/"
  weight = 2
[[menu.main]]
  name = "About"
  identifier = "about"
  url  = "/about/"
  weight = 3
  hasChildren = true
[[menu.main]]
  Name = "Organization"
  parent = "about"
  URL = "/about/organization.md"
  Weight = 1.0
[[menu.main]]
  Name = "Alumni"
  parent = "about"
  URL = "/about/alumni.md"
  Weight = 2.0
[[menu.main]]
  name = "Contact"
  url  = "/contact/"
  weight = 4

# Enable or disable top bar with social icons
[params.topbar]
  enable = false
  text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
    <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
    <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
    </p>
    """
# Top bar social links menu
[[menu.topbar]]
  weight = 1
  name = "GitHub"
  url = "https://github.com/SysBioChalmers"
  pre = "<i class='fa fa-2x fa-github'></i>"

[params]
  viewMorePostLink = "/news/"
  author = "Martina"
  defaultKeywords = ["devows", "hugo", "go"]
  defaultDescription = "Site template made by devcows using hugo"

  # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
  style = "blue"

  # Since this template is static, the contact form uses www.formspree.io as a
  # proxy. The form makes a POST request to their servers to send the actual
  # email. Visitors can send up to a 1000 emails each month for free.
  # What you need to do for the setup?
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email yourself to confirm your account
  # - click the confirm link in the email from www.formspree.io
  # - you're done. Happy mailing!
  # Enable the contact form by entering your Formspree.io email
  email = "your@email.com"

  about_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"
  copyright = "Sysbio © 2018 "

  # Format dates with Go's time formatting
  date_format = "January 2, 2006"

  logo = "img/logo.png"
  address = """<p><strong>Chalmers University of Technology</strong>
      <br>Department of Biology and Biological Engineering
      <br>Division of Systems and Synthetic Biology
      <br>Kemivägen 10
      <br>SE-412 96 Göteborg
      <br>
      <strong>Sweden</strong>
    </p>
    """
  latitude = "57.690795"
  longitude = "11.977283"

[Permalinks]
  news = "/news/:year/:month/:day/:filename/"

# Enable and disable widgets for the right sidebar
[params.widgets]
  categories = true
  tags = true
  search = true

[params.carousel]
  enable = false
  # All carousel items are defined in their own files. You can find example items
  # at 'data/carousel'. For more informtion take a look at the README.

[params.features]
  enable = true
  # All features are defined in their own files. You can find example items
  # at 'exampleSite/data/features'.
  # For more informtion take a look at the README.

[params.testimonials]
    enable = true
  # All testimonials are defined in their own files. You can find example items
  # at 'data/testimonials'. For more information take a look at the README.
  title = "Labs"
  subtitle = "We could have a one-liner here."

[params.see_more]
  enable = true
  icon = "fa fa-file-code-o"
  title = "Do you want to see more?"
  subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
  link_url = "#"
  link_text = "Check other homepages"

[params.clients]
  enable = true
  # All clients are defined in their own files. You can find example items
  # at 'data/clients'.
  # For more informtion take a look at the README.
  title = "Our Clients"
  subtitle = "Text here?"

[params.recent_posts]
  enable = true
  title = "Latest news"
  subtitle = "Optional one-liner."
