backend:
  name: github
  repo: SysBioChalmers/sysbio.se
  branch: develop

# publish_mode: editorial_workflow
media_folder: "static/img/" # Media files will be stored in the repo under static/img/
public_folder: "img/" # The src attribute for uploaded media will begin with img/

collections: # A list of collections the CMS should be able to edit
  - name: "news" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "News" # Used in the UI, ie.: "New Post"
    folder: "content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    extension: md
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Author", name: "author", widget: "select", options: ["Martina"]}
      - {label: "Categories", name: "categories", widget: "list", required: false}
      - {label: "Tags", name: "tags", widget: "list", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "people" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "People" # Used in the UI, ie.: "New Post"
    label_singular: "Person"
    folder: "content/people" # The path to the folder where the documents are stored
    filter: { field: "template", value: "people/profile"}
    create: true # Allow users to create new documents in this collection
    extension: md
    fields: # The fields each document in this collection have
      - {label: "Name and title", name: "name", widget: "string"}
      - {label: "URL, shoud be 'firstname-lastname'", name: "title", widget: "string"}
      - {label: "Last name used for sorting", name: "lastname", widget: "string"}
      - {label: "Picture", name: "picture", widget: "image"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Email", name: "email", widget: "string"}
      - {label: "Flags", name: "flags", widget: "list", required: false}
      - {label: "Person category", name: "person-category", widget: "select", options: ["A Faculty", "B Affiliated faculty", "C Extended faculty group leaders", "D Researchers", "E Postdocs", "F PhD students", "G Master students", "H Visiting researchers", "I Guests", "J Research engineers - Wet lab", "K Research engineers - Computational lab", "L Assistant manager", "M Departmental administration", "N Computational systems biology infrastructure"]}
      - {label: "Template", name: "template", widget: "select", options: ["people/profile"]}
      - {label: "Body", name: "body", widget: "markdown", required: false}

  - name: "pest-bin_eu" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "PEST-BIN EU" # Used in the UI, ie.: "New Post"
    label_singular: "PEST-BIN page"
    folder: "content/pest-bin_eu" # The path to the folder where the documents are stored
    media_folder: "img/"
    slug: "{{title}}"
    filter: { field: "template", value: "pest-bin_eu/single"}
    create: true # Allow users to create new documents in this collection
    extension: md
    fields: # The fields each document in this collection have
      - {label: "Page Title", name: "title", widget: "string"}
      - {label: "Template", name: "template", widget: "select", options: ["pest-bin_eu/single"]}
      - {label: "Image", name: "image", widget: "image", required: false, allow_multiple: true}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "GraMI" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "GraMI" # Used in the UI, ie.: "New Post"
    label_singular: "GraMI page"
    folder: "content/GraMI" # The path to the folder where the documents are stored
    slug: "{{title}}"
    filter: { field: "template", value: "GraMI/single"}
    create: true # Allow users to create new documents in this collection
    extension: md
    fields: # The fields each document in this collection have
      - {label: "Page Title", name: "title", widget: "string"}
      - {label: "Template", name: "template", widget: "select", options: ["GraMI/single"]}
      - {label: "Image", name: "image", widget: "image", required: false, allow_multiple: true}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "labs" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Labs" # Used in the UI, ie.: "New Post"
    label_singular: "Lab"
    folder: "content/labs" # The path to the folder where the documents are stored
    filter: { field: "template", value: "labs/single"}
    create: true # Allow users to create new documents in this collection
    extension: md
    fields: # The fields each document in this collection have
      - {label: "Name, eg Nielsen Lab", name: "title", widget: "string"}
      - {label: "URL, should be 'lastname'", name: "name", widget: "string"}
      - {label: "Picture", name: "picture", widget: "image"}
      - {label: "Text for the card", name: "card", widget: "string"}
      - {label: "Template", name: "template", widget: "select", options: ["labs/single"]}
      - {label: "Profile, top left box", name: "profileleftbox", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Other pages"
    files:
      - file: "content/contact.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Title", name: "title", widget: "select", options: ["Contact"]}
          - {label: "Picture", name: "picture", widget: "image"}
          - {label: "Body", name: body, widget: markdown}
      - file: "content/international-projects.md"
        label: "International projects"
        name: "international-projects"
        fields:
          - {label: "Title", name: "title", widget: "select", options: ["International projects"]}
          - {label: "Template", name: "template", widget: "select", options: ["projects"]}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/tools/databases.md"
        label: "Databases"
        name: "databases"
        fields:
          - {label: "Title", name: "title", widget: "select", options: ["Databases"]}
          - {label: "Template", name: "template", widget: "select", options: ["databases"]}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/tools/gems.md"
        label: "Gems"
        name: "gems"
        fields:
          - {label: "Title", name: "title", widget: "select", options: ["Gems"]}
          - {label: "Template", name: "template", widget: "select", options: ["ttols/gems"]}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/tools/software.md"
        label: "Software"
        name: "software"
        fields:
          - {label: "Title", name: "title", widget: "select", options: ["Software"]}
          - {label: "Template", name: "template", widget: "select", options: ["tools/software"]}
          - {label: "Body", name: "body", widget: "markdown"}
